### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by nishadsinghi** [YueYANG1996/LaBo#2]
I ran `bash labo_train.sh CIFAR_10 all` and got this error:

```
Traceback (most recent call last):
  File "/home/bethge/bkr046/LaBo/main.py", line 341, in <module>
    cfg = utils.pre_exp(args.cfg, args.work_dir)
  File "/home/bethge/bkr046/LaBo/utils.py", line 23, in pre_exp
    cfg = Config.fromfile(cfg_file)
  File "/mnt/qb/work/bethge/bkr046/anaconda3/envs/LaBo/lib/python3.9/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/mnt/qb/work/bethge/bkr046/anaconda3/envs/LaBo/lib/python3.9/site-packages/mmcv/utils/config.py", line 183, in _file2dict
    check_file_exist(filename)
  File "/mnt/qb/work/bethge/bkr046/anaconda3/envs/LaBo/lib/python3.9/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/bethge/bkr046/LaBo/cfg/asso_opt/all/all_CIFAR_10shot_fac.py" does not exist

```

Looks like this file (`cfg/asso_opt/all/all_CIFAR_10shot_fac.py`) was not added to GitHub. Could you please add it?

**Comment by YueYANG1996** [comment]
Hi, it should be `sh labo_train.sh CIFAR10 all`.

From your error message, I guess you ran `sh labo_train.sh all CIFAR_10`.

**Comment by nishadsinghi** [comment]
Thanks for the prompt reply, and apologies for the delay. I tried again, and `bash labo_train.sh CIFAR_10 all` still returns the same error. However, `bash labo_train.sh all CIFAR10` works.
