### ISSUE TITLE
GPU  for LaBo

### ISSUE THREAD

**Issue by lmg1999** [YueYANG1996/LaBo#25]
hi, I have used the config of cub_base for training , but I kept getting the error of cuda out of memory although I have reduced the batchsize to 4.  
I guess the problem may be in the step of precomputing features.
These are the error message:
Traceback (most recent call last):
  File "/home2/LaBo/main.py", line 350, in <module>
    main(cfg)
  File "/home2/LaBo/main.py", line 228, in asso_opt_main
    data_module = DotProductDataModule(
  File "/home2/lLaBo/data.py", line 378, in __init__
    super().__init__(*args, **kwargs)
  File "/home2/LaBo/data.py", line 157, in __init__
    self.prepare_img_feat(self.splits, self.n_shots, self.clip_model, self.clip_ckpt)
  File "/home2/LaBo/data.py", line 317, in prepare_img_feat
    img_feat, label = self.compute_img_feat(cls2img, n_shots if mode == 'train' else 'all', clip_model, clip_ckpt)
  File "/home2/LaBo/data.py", line 303, in compute_img_feat
    img_feat = utils.prepare_img_feat(all_img_paths,
  File "/home2/LaBo/utils.py", line 94, in prepare_img_feat
    batchify_run(process_img, img_names, res, 2048, use_tqdm=True)
  File "/home2/LaBo/utils.py", line 62, in batchify_run
    batch_res = process_fn(batch_data)
  File "/home2/LaBo/utils.py", line 91, in process_img
    img_feat = model.encode_image(img_tensor)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/clip/model.py", line 341, in encode_image
    return self.visual(image.type(self.dtype))
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/clip/model.py", line 148, in forward
    x = self.layer1(x)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/clip/model.py", line 48, in forward
    out = self.bn3(self.conv3(out))
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 175, in forward
    return F.batch_norm(
  File "/home2/anaconda3/envs/labo/lib/python3.9/site-packages/torch/nn/functional.py", line 2482, in batch_norm
    return torch.batch_norm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.06 GiB. GPU 1 has a total capacity of 10.91 GiB of which 552.62 MiB is free. Including non-PyTorch memory, this process has 10.36 GiB memory in use. Of the allocated memory 6.56 GiB is allocated by PyTorch, and 3.08 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

could you give me some advice ?   Shoud I try a higher GPU ?thanks a lot!

**Comment by YueYANG1996** [comment]
For training ImageNet, you need a GPU with 40GB memory, for the rest datasets, 24GB should be enough.

**Comment by lmg1999** [comment]
Ok ,thanks! I try to use 3090 and get the true result.
